[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm run develop"
healthcheckPath = "/_health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.lifecycle]
preStartCommand = "node ./config/functions/bootstrap.js" 